apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: eriop
  labels:
    app: mosquitto
    component: mqtt-broker
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/part-of: eriop-platform
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - port: 8883
      targetPort: mqtt-tls
      protocol: TCP
      name: mqtt-tls
    - port: 1883
      targetPort: mqtt-internal
      protocol: TCP
      name: mqtt-internal
